apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calrissian-session.fullname" . }}
  labels:
    {{- include "calrissian-session.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "calrissian-session.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "calrissian-session.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: container-rg-config
      serviceAccountName: {{ template "serviceaccount_name" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          lifecycle:
            postStart:
              exec:
                {{- if .Values.s3.enabled }}
                command: ["/bin/sh", "-c", "cp -r /home/.docker /workspace/.podman && cp -r /home/.aws /workspace/.aws && chown -R mambauser:100 /workspace/.podman && chown -R mambauser:100 /calrissian" ]  
                {{ else }}
                command: ["/bin/sh", "-c", "cp -r /home/.docker /workspace/.podman && chown -R mambauser:100 /workspace/.podman && chown -R mambauser:100 /calrissian" ]
                {{ end }}
          command: ["sleep"]
          args: ["604800"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /calrissian
            name: calrissian-volume
            readOnly: false
          - mountPath: /workspace/node-selector.yaml
            name: node-selector
            subPath: node-selector
          {{- if .Values.s3.enabled }}
          - name: aws-config
            mountPath: /home/.aws/config
            subPath: aws-config
          - name: aws-credentials
            mountPath: /home/.aws/credentials
            subPath: aws-credentials
          - name: user-settings
            mountPath: /etc/Stars/appsettings.json
            subPath: user-settings
          {{- end }}  
          - name: container-registry
            mountPath: /home/.docker/config.json
            subPath: container-registry
          env:
          - name: CALRISSIAN_POD_NAME
            valueFrom: {fieldRef: {fieldPath: metadata.name}}
          - name: XDG_RUNTIME_DIR
            value: /workspace/.podman
          - name: HOME
            value: /workspace
          {{- if .Values.s3.enabled }}
          - name: AWS_DEFAULT_REGION
            value: {{ .Values.s3.region }}
          - name: AWS_REGION
            value: {{ .Values.s3.region }}
          - name: S3_SERVICE_URL
            value: {{ .Values.s3.endpoint_url }}
          - name: AWS_SECRET_ACCESS_KEY
            value: {{ .Values.s3.secret_access_key }}
          - name: AWS_ACCESS_KEY_ID
            value: {{ .Values.s3.access_key_id }}
          {{- end }}
      volumes:
      - name: calrissian-volume
        persistentVolumeClaim:
          claimName: calrissian-volume
          readOnly: false
      - name: node-selector
        configMap:
          name: node-selector
      {{- if .Values.s3.enabled }}
      - name: aws-config
        configMap:
          name: aws-config
      - name: aws-credentials
        configMap:
          name: aws-credentials
      - name: user-settings
        configMap:
          name: user-settings
      {{- end }}
      - name: container-registry
        configMap:
          name: container-registry
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
