apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calrissian-volume
  annotations:
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.calrissian | quote }}
  storageClassName: {{ .Values.storageClass }}
