apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calrissian-input-data
  annotations:
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.input | quote }}
  storageClassName: {{ .Values.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calrissian-tmpout
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.tmp | quote }}
  storageClassName: {{ .Values.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calrissian-output-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.output | quote }}
  storageClassName: {{ .Values.storageClass }}
