{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  #name: {{ include "calrissian-session.serviceAccountName" . }}
  name: {{ template "serviceaccount_name" . }}
  labels:
    {{- include "calrissian-session.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
- name: container-rg-config
{{- end }}
