# Default values for calrissian-session.

# -- number of pods, one is usually enough
replicaCount: 1

# -- Calrissian container image for running the Calrissian pod
image:
  repository:  ghcr.io/terradue/calrissian-session/calrissian-session
  pullPolicy: Always
  tag: latest

# -- specify the resources for the Calrissian pod
resources:
  requests:
    memory: "8Gi"
    cpu: "4"
  limits:
    memory: "12Gi"
    cpu: "4"

# -- Service account to use
serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  name: "calrissian-sa"

# -- optional pod annotations
podAnnotations: {}

# -- additional settings for the pod security context
podSecurityContext: {}

# -- running with privileged set to true allows running podman in the Calrissian pod
securityContext: 
  privileged: true

# -- specify the node selector for the Calrissian pod and the Calrissian worker pods
nodeSelector: 
  k8s.scaleway.com/pool-name: processing-node-pool-iride-xl

# -- tolerations
tolerations: []

# -- node affinity
affinity: {}

# -- ReadWriteMany storage class for Calrissian worker 
storageClass: openebs-kernel-nfs-scw
# -- size of the ReadWriteMany volume for Calrissian executions
volumeSize: 10Gi


# -- use s3, if true, configMaps are mounted to access the S3 bucket
s3:
  enabled: true
  access_key_id: "SC...8Z"
  secret_access_key: "bf...dc6"
  region: "..."
  endpoint_url: "https://s3.....cloud"
  signature_version: s3v4
  bucket_pattern: 's3:\/\/ir....tplace\/.*'

# -- container registries credentials
imageCredentials:
    # -- registry is the container registry
  - registry: ghcr.io # mandatory
    # -- auth is the base64 auth string (see your ~/.docker/config.json file)
    auth: "bXNhZ2....RVURt"
  - 'https://index.docker.io/v1/':
    auth: "ZmFi...mlRTldqZw=="